version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/src/PDFtoImage"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    groups:
      pdfium:
        patterns:
          - "bblanchon.PDFium.*"
      skiasharp:
        patterns:
          - "SkiaSharp"
          - "SkiaSharp.NativeAssets.*"